### ISSUE TITLE
Video Playback

### ISSUE THREAD

**Issue by iamrellah** [EthanArbuckle/carplay-cast#10]
First of all, thank you very much for this tweak and the work that was put into this. I will personally use this while charging my car on longer trips. While charging and parked watching a movie will be great.

After some trial and error i found out not all apps work with video playback. For example if i stream a movie using Plex it does work but playback using the Disney+ app does not. Is this caused by DRM security on these apps or might this be somehow codec related?

**Comment by dareal68** [comment]
Hi, it is DRM related. You can do a screenshot of the app you want to test, if the result is a black image, it is DRM.
Netflix, Disney+, Prime Video will not work...
