### ISSUE TITLE
Dolphin iOS/Kodi support - Sideloaded apps may not appear

### ISSUE THREAD

**Issue by iamrellah** [EthanArbuckle/carplay-cast#11]
Would support for Dolpin iOS or Kodi for example be possible? Would be awesome to play games while being parked using a controller

**Comment by EthanArbuckle** [comment]
Does it not work now?

**Comment by iamrellah** [comment]
@EthanArbuckle The apps aren't showing up in Carplay at the moment, does that mean they should be showing? I thought there might be a difference between "Appstore Apps" and Apps installed which are not in the Appstore like Kodi or Dolphin iOS. 
Thank you for all the effort put into this! 😃

**Comment by EthanArbuckle** [comment]
oh i see, they're not from the Appstore. I'll look into this

**Comment by EthanArbuckle** [comment]
fixed in https://github.com/EthanArbuckle/carplay-cast/commit/76261d7560f10bf61a34bc7bb01dd29de9315726

**Comment by iamrellah** [comment]
@EthanArbuckle when can we expect an updated deb file/repo update? Thank you for fixing this 😃

**Comment by EthanArbuckle** [comment]
update is here and on the repo https://github.com/EthanArbuckle/carplay-cast/releases/tag/0.0.1-5

**Comment by XqqsMe** [comment]
Does one have to have a jailbroken phone for this tweak to work? I have the iPhone 12 Pro Max.

**Comment by iamrellah** [comment]
@EthanArbuckle i've been testing the Dolphin iOS on Carplay, it seems that there is a locked framerate, for some reason the FPS is locked to 30fps on the Carplay screen while the iPhone screen will give me 60fps. Would you perhaps know if this is a limitation to Carplay itself?

**Comment by EthanArbuckle** [comment]
Many CarPlay radios only support 30fps. If will use 60fps if the hardware supports it
