### ISSUE TITLE
Can I change the status bar to the right side? 

### ISSUE THREAD

**Issue by xackey2001** [EthanArbuckle/carplay-cast#13]
Thank you for this nice tweak! Can I change the status bar from the left to right? Because the steering wheel of my car is on the right side, not the left.

**Comment by XqqsMe** [comment]
Hi,
Can you help me get this installed on my iPhone please? I’d really appreciate it.

**Comment by vpww** [comment]
> Thank you for this nice tweak! Can I change the status bar from the left to right? Because the steering wheel of my car is on the right side, not the left.
 
 i think it can be changed in your headunit settings

**Comment by xackey2001** [comment]
@vpww 
Unfortunately, I can't find any option like that in my head unit settings.

**Comment by meccabolix** [comment]
The RHD Dock orientation does seem to be linked to the head unit, but most head units don't seem to give you the choice to change it. When RHD drivers use carplay it automatically puts the Dock on the right hand side, so there's probably a little bit of code Apple put in to read the country the head unit is set to and orientates the Dock to make it easier for RHD or LHD.

**Comment by EthanArbuckle** [comment]
agreed - i will add this

**Comment by EthanArbuckle** [comment]
added in https://github.com/EthanArbuckle/carplay-cast/commit/796fcd6063766913b5776bee61a5a786674e2bd9

**Comment by gill6151** [comment]
> When RHD drivers use carplay it automatically puts the Dock on the right hand side, so there's probably a little bit of code Apple put in to read the country the head unit is set to and orientates the Dock to make it easier for RHD or LHD.

I am aware this issue is now closed but i am able to confirm that this is not true, what side the carplay status bar is on is entirely dependent on the headunit settings
t. RHD driver
