### ISSUE TITLE
Support vehicles without a touch screen

### ISSUE THREAD

**Issue by yeonho84lee** [EthanArbuckle/carplay-cast#17]
Mercedes vehicles without a touch screen can do nothing. Carplay is originally fully used as a jog dial (wheel).
Can you help me enjoy your tweak with it?? :)

**Comment by dareal68** [comment]
#1

**Comment by mantronix89** [comment]
I also faced such a problem on Mercedes, please make support for the joystick.

**Comment by xoniq** [comment]
Same on my new Mazda CX-30. My previous car had a touch screen, this one doesn't.
