### ISSUE TITLE
why some user have the carplayenable settings,some dont

### ISSUE THREAD

**Issue by cnRobinHood** [EthanArbuckle/carplay-cast#18]
![Screenshot_2021-01-22-22-02-20-083_com tencent mobileqq](https://user-images.githubusercontent.com/22888401/105500431-e1d13e80-5cfd-11eb-9249-6f63a23de9b3.jpg)
many thanks to your app,i will be very appreciate if you can solve my confuse.and hope you can provide the build steps in the future.

**Comment by xackey2001** [comment]
@cnRobinHood, @EthanArbuckle 

The settings appeared after I deleted and reinstalled the carplayenable. But I do not know where can I change the dock alignment preference. Can anyone help?

**Comment by EthanArbuckle** [comment]
they are using a newer version

**Comment by cnRobinHood** [comment]
> they are using a newer version

thanks for your reply,i have figured it out after i installed  Liberty and Respring.i dont know why.btw,i am useing the same version with them.
