### ISSUE TITLE
Possible port to ios 13?

### ISSUE THREAD

**Issue by narcyzzo** [EthanArbuckle/carplay-cast#2]

**Comment by Wo1v3rine** [comment]
What kind of help do you need ?
Testing ?

**Comment by Gismo567** [comment]
iOS 13.5 iPhone X pls how can i Test it for you?

**Comment by louij2** [comment]
+1

**Comment by jimhatesyou** [comment]
Would absolutely LOVE iOS 13 support. Currently on 13.5 unc0ver, no way to be on iOS 14 jailbroken for my iPhone 11 Pro Max.

**Comment by EthanArbuckle** [comment]
It's not something I'll be doing. Some other developers have shown interest in creating their own iOS 13 fork

**Comment by jimhatesyou** [comment]
Thank you for the reply. Someone on Reddit leftyfl1p had posted an iOS 13 fork but it does nothing for me. Anyway, understandable and I do appreciate the response 👍🏽
  
  
  
    
  

  
  
>
