### ISSUE TITLE
Adding apps to Home Screen/ No mirror

### ISSUE THREAD

**Issue by Nunyabizzdamnit** [EthanArbuckle/carplay-cast#21]
iOS 14.3
CarPlayenable/CarPlay-Cast

Just updated and can’t find any preferences or options to add any new apps to the new 4x2 layout. Previous version had 5x2 layout and most apps available to use. Also can’t find any app to simply mirror iPhone 8 Plus screen (unless I missed where that is no longer an option ). Awesome tweak someone finally gave attention to and just wanting to let you know personal experience with current version and if I’m doing something wrong.
Thanks

**Comment by EthanArbuckle** [comment]
Can you try uninstall and reinstall? Not sure what the issue could be, but it sounds like the tweak isnt getting injected

**Comment by Nunyabizzdamnit** [comment]
> Can you try uninstall and reinstall? Not sure what the issue could be, but it sounds like the tweak isnt getting injected

I’ll give it a shot and let u know what happens. Thanks

**Comment by EthanArbuckle** [comment]
did it stop working only after updating to the latest version?

**Comment by Nunyabizzdamnit** [comment]
> did it stop working only after updating to the latest version?

Sorry for the late reply. Been deleting, adding, editing, moving things around to make things hopefully work but seem to still be at same junction. I touch add/delete button to put apps on carplay-cast/carplayenable and it just goes darker grey (like it responds when I touched it) but doesn't open anything up or go to selection screen. Also when plug into my car radio only normal, boring carplay comes up. Only doing it on the newest 6 release and I'm confused as hell lol.

**Comment by Nunyabizzdamnit** [comment]
Well I'll close this issue out cause it decided it wanted to show up under my settings and it let me add/remove apps. 

Technology...its self aware. 

Tremendous kudos on the tweak. Even more so that everything decided to work.

**Comment by EthanArbuckle** [comment]
Cool, thanks!

**Comment by Nunyabizzdamnit** [comment]
> Cool, thanks!

Yessir
