### ISSUE TITLE
Help a newbe

### ISSUE THREAD

**Issue by crowe769** [EthanArbuckle/carplay-cast#22]
Very new to the apple and jailbreak game. I have jail broken my phones. And I have before installed from Github. But I can’t get this one installed and it is driving me insane carbridge is why I got into iPhones and jail breaking. This app of yours is what I’ve wanted from the start. Can anyone just give me a step by step

**Comment by XqqsMe** [comment]
I’m in the same boat as well. I’ve asked and never received a response so far. I think I may have figured out what to do but not 100% sure. I have an iPhone 12 Pro Max and will have to wait for a jailbreak before I can try it.

**Comment by crowe769** [comment]
Well I wish you all the luck in the world please let me know if it works
I’m using a couple phones iPhone 8 plus an iPhone 8 and an XR that I
accidentally let update so now I have to wait on jailbreak for it
