### ISSUE TITLE
Not able to uncheck apps, iOS 14.4

### ISSUE THREAD

**Issue by 4uba** [EthanArbuckle/carplay-cast#44]
When I uncheck apps, it’s still on CarPlay. 
Respring doesn’t help. But for example if I move dock (dock alignment) I see changes immediately. 
can you please check it for iOS 14.4?

**Comment by tloki** [comment]
Also on 14.2

**Comment by EthanArbuckle** [comment]
latest build fixes this issue. It will be on bigboss tomorrow, and is available now at repo.ghostbin.co
