### ISSUE TITLE
Double screenshot

### ISSUE THREAD

**Issue by benklinger** [EthanArbuckle/carplay-cast#45]
**Describe the bug**
Device thinks a second screen is present when it isn't.

**To Reproduce**
1. Disconnect CarPlay.
2. Take screenshot.
3. Two screenshots taken - iPhone screen and a black image.

**Expected behavior**
When not connected to CarPlay, only one screenshot should be taken.

**iOS Version:**
 - iOS 14.2

**Comment by EthanArbuckle** [comment]
fixed in next release
