### ISSUE TITLE
Ghostbin repo down over a week now 

### ISSUE THREAD

**Issue by denali24s** [EthanArbuckle/carplay-cast#48]
The ghostbin repo has been down now for a while and causing issues to installed carplayenable on device? 
![5654C353-7E29-43D3-AA71-870FBAC78207](https://user-images.githubusercontent.com/76881909/109156844-56552e00-773f-11eb-9f88-7f159edb5efd.jpeg)

**Comment by EthanArbuckle** [comment]
fixed
