### ISSUE TITLE
Default CarPlay on an Iphone 7 IOS 14.4 jailbroken with OdysseyRa1n

### ISSUE THREAD

**Issue by Yuri989** [EthanArbuckle/carplay-cast#49]
When i connect my phone to my car only the default CarPlay appears.I can't use 3d touch on default apps because it does nothing.

To try to fix the problem i used Libhooker configurator and put CarplayEnable in the substrate compatibility mode but it did nothing more.

Edit: Forgot to mention, the tweak appears in settings and I can choose which apps are supposed to appear on CarPlay but even if all the apps are selected to show up none of them actually shows up on my CarPlay screen

**Comment by EthanArbuckle** [comment]
this is a libhooker issue. I can't work around it as I dont have an OdysseyRa1n device (and the libhooker developer does not make the package available to other jailbreaks)
