### ISSUE TITLE
Invalid with unc0ver6.0 A14 iOS14.3

### ISSUE THREAD

**Issue by silentcloud** [EthanArbuckle/carplay-cast#50]
Thanks for this tweak, the only thing to my jailbroken

After installation with unc0ver6.0, iOS 14.3, A14(iPhone12 mini), Only  original Carplay, It looks like the tweak is invalid

And error in settings 

![D50ED3A2-D4BB-4D81-A8E0-A5D89936FF6F](https://user-images.githubusercontent.com/1698185/109411173-1f02ad80-79db-11eb-8d99-630808d80e23.jpeg)

**Comment by Dark976** [comment]
same thing here with iOS14.1 and A13.

**Comment by christopherhahlbeck** [comment]
Same here, iOS 14.2.1, iPhone 12 pro, Unc0ver 6 JB

**Comment by mattkerrison** [comment]
Same with iphone 11 pro & 14.1

**Comment by Fateliu** [comment]
Same here, iOS 14.2 iPhone 12 Pro Max, Unc0ver 6 JB

**Comment by jly26** [comment]
no issues with ipX 14.3 UC 6 JB..but I cant hide apps

**Comment by HaxForan** [comment]
Same issue here with iPhone 11 uncover 6.0 ios 14. Thanks for ur help

**Comment by totoscania** [comment]
Same issue here with iPhone XS uncover 6.0 ios 14.3  Thanks for ur help

**Comment by Arcrocus** [comment]
Same thin with iphone 11, iOS 14.0.1. 
need your help 🥺

**Comment by crisvt10** [comment]
Alguien supo cómo se arregla ese problema ?

**Comment by Baw-Appie** [comment]
https://drive.google.com/file/d/106HjlUoQXC3ovPUq_I3Ei3kvcm5jbjGN/view?usp=sharing
Try this deb

**Comment by EthanArbuckle** [comment]
Please try the latest build from https://repo.ghostbin.co. Version 1.0.1-1

**Comment by hungdaddyyy** [comment]
> Please try the latest build from https://repo.ghostbin.co. Version 1.0.1-1

I just did that on my iPhone 12 , iOS 14.3 uncover 6, it caused my phone to reboot every time I try to open the settings page. 

Also didn’t let me enter jailbreak mode again , had to disable tweaks injection and then jailbreak from uncover

**Comment by hungdaddyyy** [comment]
> > Please try the latest build from https://repo.ghostbin.co. Version 1.0.1-1
> 
> I just did that on my iPhone 12 , iOS 14.3 uncover 6, it caused my phone to reboot every time I try to open the settings page.
> 
> Also didn’t let me enter jailbreak mode again , had to disable tweaks injection and then jailbreak from uncover

The only other tweaks I have installed are Plus for Instagram , AudioRecorderXS . 
I don’t have apple file conduit installed, could that be it ?

**Comment by crisvt10** [comment]
> Pruebe la última compilación de https://repo.ghostbin.co. Versión 1.0.1-1

thanks !!

**Comment by hungdaddyyy** [comment]
The tweak caused my phone to restart every time I tried opening the settings page. 
Problem was solved after installing apple file conduit 2 (afc2). Thanks a lot.

**Comment by EthanArbuckle** [comment]
@hungdaddyyy afc2 should not be required. I will try to reproduce this issue and fix. Thanks for reporting
