### ISSUE TITLE
Stock apps like Mail, Safari, etc. not showing up in selection menu.

### ISSUE THREAD

**Issue by Detr0x** [EthanArbuckle/carplay-cast#61]
**Describe the bug**

Stock apps like Mail, Safari, etc. not showing up in selection menu.

**To Reproduce**
1. Go to settings -> CarPlayEnable-> Add/Remove apps
2. Stock apps like Mail, Safari, etc. not present

**Expected behavior**
Stock apps like Mail, Safari should be present to be selected.

**iOS Version (please complete the following information):**
 - iOS 14.1 (iPhone 12 Pro Max)

**Comment by saeedbalkhair** [comment]
I hope that this will be solved in future updates
