### ISSUE TITLE
Portrait/Landscape

### ISSUE THREAD

**Issue by Zhimiping** [EthanArbuckle/carplay-cast#62]
Hello, I have been experiencing portrait/landscape issues when plugging in to CarPlay app will not go into landscape view automatically? Is anyone else experiencing similar issues? Thank you
![1AF4AFE1-FBCB-4C8A-818B-947ADC59BE28](https://user-images.githubusercontent.com/37589786/112738797-43818380-8fa1-11eb-8eb9-020a1f56ea5f.png)
![50BCB897-EC7E-49E3-B924-66D461FCFD0C](https://user-images.githubusercontent.com/37589786/112738799-4b412800-8fa1-11eb-8705-38ac1df7c38d.png)
![503DAB1E-0B00-472B-BF1B-39C750EEB4E8](https://user-images.githubusercontent.com/37589786/112738800-4c725500-8fa1-11eb-9502-cb317a484fa3.png)

**Comment by Zhimiping** [comment]
Device: iPhone 6s, iOS 14.4

**Comment by Zhimiping** [comment]
Device: iPhone 8 plus, iOS 14.4

**Comment by Zhimiping** [comment]
1.0.1-1+debug No this bug.

**Comment by js998** [comment]
Yup. Bug present on the lastest version. 1.0.1-1+debug works just fine.
