### ISSUE TITLE
Tweak not working on Taurine jailbreak 

### ISSUE THREAD

**Issue by narcyzzo** [EthanArbuckle/carplay-cast#63]
Unfortunafely this not work with taurine jailbreak on libhooker injecting platform. Tested with „substrate compatibility mode” in libhooker configurator too, same result.

**Comment by kruumy** [comment]
Same for me. I hope this will get updated eventually.

**Comment by kavaboy** [comment]
Same here 
Hope there will be a fix

**Comment by alexich111** [comment]
The same issue.

**Comment by techx-guy** [comment]
Same :( please update compatibility with taurine

**Comment by EthanArbuckle** [comment]
an update has been submitted to BigBoss that adds support for Taurine. It should be available in the next day or so

**Comment by AnthonyGress** [comment]
You’re the man! Thank you!!

**Comment by kavaboy** [comment]
Thank you kindlyLet me know where can I donate,your work truly appreciated,thank you again 


Sent from Yahoo Mail for iPhone


On Sunday, April 18, 2021, 4:59 AM, Ethan Arbuckle ***@***.***> wrote:




an update has been submitted to BigBoss that adds support for Taurine. It should be available in the next day or so
