### ISSUE TITLE
Can support TrollStore?

### ISSUE THREAD

**Issue by m5099m** [EthanArbuckle/carplay-cast#76]
It’s can work with TrollStore? 🙏🏽

**Comment by EthanArbuckle** [comment]
No, the amount of re-architecting required would just warrant making a new project for that use-case. This tweak is too reliant on injection into system processes.

I've heard from other developers that they're working on something like this for Trollstore

**Comment by Gullzway** [comment]
This would be great! It is the only thing I'm missing on my 13 Mini that I can do with my Jailbroken SE.
If I had any clue how to do this, I would contribute.
